workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands: 
      - go get github.com/Masterminds/glide
      - glide install
      
    
