workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands: 
      - go get github.com/Masterminds/glide
      - glide install
      - go build .
      
  publish:
    github_release:
      image: plugins/github_release
      api_key: my_github_api_key
      files:
        - ./glogchain
        
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
