workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands: 
      - go get github.com/Masterminds/glide
      - glide install
      
pipeline:
  github_release:
    image: plugins/github-release
    files:
      - src/github.com/dawn-network/glogchain/glogchain
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
    
