workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get github.com/Masterminds/glide
      - go get github.com/gorilla/rpc
      - glide install
      - go build .
      
  publish:
    docker:
      repo: faddat/glogchain
      email: faddat@gmail.com
      image-name: glogchain        
      push_latest: true
      keep_builds: false
      username: faddat
      password: docker_password
      tag: [ "latest" ]
      when:
        branch: master
        event: push
    github:
      branch: master
      script:
        - make embed
        - make release
      artifacts:
        - release/
      tag: v$(cat VERSION)
      token: 
      user: faddat
      repo: dawn-network/glogchain
      
  
      
