workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    branch: master
    artifacts:
      - glogchain
    commands:
      - go get github.com/Masterminds/glide
      - go get github.com/gorilla/rpc
      - glide install
      - go build .
      
  publish:
    docker:
      repo: faddat/glogchain
      email: faddat@gmail.com
      image: golang:1.8
      image-name: glogchain        
      push_latest: true
      keep_builds: false
      username: faddat
      password: docker_password
      tag: [ "latest" ]
      when:
        branch: master
        event: push
    github:
      branch: master
      artifacts:
        - glogchain
      tag: v$(cat VERSION)
      token: my_github_api_key
      user: faddat
      repo: dawn-network/glogchain
