workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands: 
      - go get github.com/Masterminds/glide
      - glide install
      
 publish:
  github_release:
    api_key: my_github_api_key
    files:
      - src/github.com/dawn-network/glogchain
      
notify:
  downstream:
    repositories:
      - dawn-network/dawnos
    token: drone_token
    when:
      event: push
      branch: master
      success: true
