workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands: 
      - go get github.com/Masterminds/glide
      - glide install
      
gh_publish:
  github_release:
    image: plugins/github_release
    api_key: my_github_api_key
    files:
      - src/github.com/dawn-network/glogchain
      

bt_publish:
  bintray:
    username: faddat
    password: bintray_password
    branch: master
    artifacts: 
      - file: bin/glogchain
        owner: dawn-network
        type: executable
        repository: dawn-network/glogchain
        package: glogchain
        target: glogchain
        publish: true
        override: true

      
notify:
  downstream:
    repositories:
      - dawn-network/dawnos
    token: drone_token
    when:
      event: push
      branch: master
      success: true
      
