workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get github.com/Masterminds/glide
      - go get github.com/gorilla/rpc
      - glide install
      - go build .
      
  publish:
    image: plugins/docker
    repo: faddat/glogchain
    username: faddat
    password: docker_password
    tag: [ "latest" ]
    when:
      branch: master
      event: push
      
