workspace:
  base: /go
  path: src/github.com/dawn-network/glogchain

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get github.com/Masterminds/glide
      - go get github.com/gorilla/rpc
      - glide install
      - go build .
  publish:
    github_release:
      image: plugins/github_release
      api_key: my_github_api_key
      files:
        - ./glogchain        
  publish:
    image: plugins/docker
    repo: drone/drone
    username: faddat
    password: docker_password
    tag: [ "latest" ]
    when:
      branch: master
      event: push
